# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#100f0f"

# Title color for boxes
theme[title]="#66800b"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#66800b"

# Background color of selected item in processes box
theme[selected_bg]="#66800b"

# Foreground color of selected item in processes box
theme[selected_fg]="#cecdc3"

# Color of inactive/disabled text
theme[inactive_fg]="#100f0f"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#66800b"

# Cpu box outline color
theme[cpu_box]="#b7b5ac"

# Memory/disks box outline color
theme[mem_box]="#b7b5ac"

# Net up/down box outline color
theme[net_box]="#b7b5ac"

# Processes box outline color
theme[proc_box]="#b7b5ac"

# Box divider line and small boxes line color
theme[div_line]="#fffcf0"

# Temperature graph colors
theme[temp_start]="#66800b"
theme[temp_mid]="#66800b"
theme[temp_end]="#af3029"

# CPU graph colors
theme[cpu_start]="#66800b"
theme[cpu_mid]="#66800b"
theme[cpu_end]="#af3029"

# Mem/Disk free meter
theme[free_start]="#66800b"
theme[free_mid]=""
theme[free_end]="#e6e4d9"

# Mem/Disk cached meter
theme[cached_start]="#66800b"
theme[cached_mid]=""
theme[cached_end]="#e6e4d9"

# Mem/Disk available meter
theme[available_start]="#66800b"
theme[available_mid]=""
theme[available_end]="#163b66"

# Mem/Disk used meter
theme[used_start]="#af3029"
theme[used_mid]=""
theme[used_end]="#f9dedc"

# Download graph colors
theme[download_start]="#66800b"
theme[download_mid]="#66800b"
theme[download_end]="#66800b"

# Upload graph colors
theme[upload_start]="#66800b"
theme[upload_mid]="#66800b"
theme[upload_end]="#66800b"
