cursor #cecdc3
cursor_text_color #cecdc3

foreground            #cecdc3
background            #100f0f
selection_foreground  #100f0f
selection_background  #879a39
url_color             #879a39

color0   #100F0F
color1   #cd604c
color2   #429a38
color3   #c0ad3b
color4   #7c9223
color5   #394700
color6   #879A39
color7   #9fa195
color8   #77796f
color9   #cf7b6d
color10  #6fb867
color11  #e6d881
color12  #97a94e
color13  #b6c86f
color14  #cbd79a
color15  #dddfd8
